
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineLibrary.Domain.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Books
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Books()
    {

        this.Loans = new HashSet<Loans>();

    }


    public int ID { get; set; }

    public string Title { get; set; }

    public int Year { get; set; }

    public string ISBN { get; set; }

    public int AuthorID { get; set; }

    public string imageURL { get; set; }

    public int NoOfBooks { get; set; }

    public int CategoriesID { get; set; }

    public int PublishingsID { get; set; }

    public string Description { get; set; }



    public virtual Authors Author { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Loans> Loans { get; set; }

    public virtual Categories Category { get; set; }

    public virtual Publishings Publishing { get; set; }

}

}
